# Kext version only incremented when there were actual changes in the kext, so
# effectively the kext version is the xnumon release it last changed.

KEXTNAME=	xnumon
KEXTVERSION=	0.1.0
KEXTBUILD=	0.1.0
BUNDLEDOMAIN=	ch.roe

MACOSX_VERSION_MIN=	10.11

#DEVIDKEXT=	"Developer ID Kext: Daniel Roethlisberger (C9BFEG985N)"
#CFLAGS=	-Wno-\#warnings
#KLFLAGS=	-unsupported

include Mk/kext.mk
