#!/bin/sh
# $1  Full path to package
# $2  Full path to target installation directory: /Applications
# $3  Mountpoint of installation disk: / or /Volumes/ExtDrive
# $4  Root directory of currently booted system
set -e
if [ "$3" != "/" ]; then
	exit 0
fi
if /bin/launchctl list ch.roe.xnumon >/dev/null 2>&1; then
	if [ -f /var/run/xnumon.pid ]; then
		pid=`cat /var/run/xnumon.pid`
	else
		pid=`killall -u root -s xnumon|cut -f 3 -d ' '|head -1 2>/dev/null || true`
	fi
	/bin/launchctl remove ch.roe.xnumon
	if [ "x$pid" != "x" ]; then
		while ps -p "$pid" -o comm= >/dev/null; do sleep 1; done
	else
		sleep 10
	fi
fi
exit 0
